--- 
pool: 
  vmImage: ubuntu-latest
steps: 
  - 
    script: "echo Execution Set will start executing now   \n"
  - 
    script: "curl -X POST "https://platform.subject-7.com/api/v2/executions/latest" -H  "accept: application/json" -H  "X-API-KEY: YXV0b21hdGlvbg==.U3ViamVjdDc=.dGVzdF9hdXRvbWF0aW9u.f4be5839051f4ac4b3b4fa320500ecfb" -H  "Content-Type: application/json" -d "[{\"executionSetName\":\"firas_test_apr1\",\"projectName\":\"Common\",\"versionName\":\"default\"}]""
trigger: 
  - main